name: Build and Upload

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Rust
      uses: actions/setup-rust@v1

    - name: Build the Rust application
      run: cargo build --release

    - name: Upload to S3
      run: |
        aws s3 cp ./target/release/xhtp s3://xhtp/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-north-1'

    - name: Cleanup
      run: cargo clean
